// Auto Generated by North Sky
// You may modify this file if the format is not changed.

page[0]="/guestbook.html/faqs.html/fsguest.html"; count[0]=1;
page[1]="/guestbook.html/fsguestbook.html"; count[1]=1;
page[2]="/guestbook.html/main.html/main.html/projects.html"; count[2]=1;
page[3]="/drawings.html"; count[3]=1420;
page[4]="/linkage.html"; count[4]=1195;
page[5]="/guestbook.html/main.html/me.html"; count[5]=1;
page[6]="/me.html"; count[6]=1286;
page[7]="/guestbook.html/main.html"; count[7]=1;
page[8]="/guestbook.html/linkage.html/links.html/projects.html"; count[8]=1;
page[9]="/guestbook.html/fsguestbook.html/projects.html"; count[9]=1;
page[10]="/guestbook.html/faqs.html"; count[10]=1;
page[11]="/guestbook.html/linkage.html"; count[11]=1;
page[12]="/main.html"; count[12]=17160;
page[13]="/linkage.html/trackback/"; count[13]=1;
page[14]="/guestbook.html/drawings.html"; count[14]=1;
page[15]="/faqs.html"; count[15]=1188;
page[16]="/guestbook.html/faqs.html/links.html"; count[16]=1;
page[17]="/guestbook.html/linkage.html/links.html/me.html"; count[17]=1;
page[18]="/drawings.html/faqs.html"; count[18]=1;
page[19]="/guestbook.html/main.html/drawings.html"; count[19]=1;
page[20]="/projects.html"; count[20]=1129;
page[21]="/guestbook.html"; count[21]=2502;
page[22]="/links.html"; count[22]=1310;
page[23]="/guestbook.html/linkage.html/links.html"; count[23]=1;
page[24]="/guestbook.html/"; count[24]=1;
page[25]="/guestbook.html/linkage.html/links.html/fsguest.html"; count[25]=1;
page[26]="/guestbook.html/main.html/main.html"; count[26]=1;
page[27]="/linkage.html/drawings.html"; count[27]=1;
page[28]="/projects.html/me.html"; count[28]=1;
